id: "Logic"
title: STRINGS.CODEX.AUTOMATION.TITLE

contentContainers:
#-----------------------------
  - contentLayout: Vertical
    lockID:
    content:    
      - !CodexText
          stringKey: STRINGS.CODEX.AUTOMATION.HEADER_1
          style: Subtitle
      - !CodexText
          stringKey: STRINGS.CODEX.AUTOMATION.PARAGRAPH_1
          style: Body
      - !CodexText
          stringKey: STRINGS.CODEX.AUTOMATION.HEADER_2
          style: Subtitle
      - !CodexText
          stringKey: STRINGS.CODEX.AUTOMATION.PARAGRAPH_2
          style: Body
      - !CodexText
          stringKey: STRINGS.CODEX.AUTOMATION.HEADER_3
          style: Subtitle
      - !CodexText
          stringKey: STRINGS.CODEX.AUTOMATION.PARAGRAPH_3
          style: Body
      - !CodexText
          stringKey: STRINGS.CODEX.AUTOMATION.HEADER_4
          style: Subtitle
      - !CodexText
          stringKey: STRINGS.CODEX.AUTOMATION.PARAGRAPH_4
          style: Body